name: Daily Scraper

on:
  schedule:
    # Minden nap reggel 8-kor és este 8-kor (UTC idő szerint)
    - cron: '0 8,20 * * *'
  workflow_dispatch: # Ez engedi, hogy kézzel is elindítsd teszteléshez

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kód letöltése
        uses: actions/checkout@v3

      - name: Python beállítása
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Csomagok telepítése
        run: |
          pip install -r requirements.txt

      - name: Script futtatása
        env: # Itt adjuk át a titkos kulcsokat a Pythonnak
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python scraper.py
