name: Hardverapro Watcher

on:
  schedule:
    - cron: '*/5 * * * *' # 1 percenként fut
  workflow_dispatch:

permissions:
  contents: write # EZ KELL ahhoz, hogy menteni tudjon!

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Kód letöltése
        uses: actions/checkout@v3

      - name: Python beállítása
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Csomagok telepítése
        run: pip install -r requirements.txt

      - name: Scraper futtatása
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python scraper.py

      - name: Változások mentése (hogy ne küldje újra)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update seen ads list"
          file_pattern: seen_ads.txt
      - name: Upload debug info
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots
          path: |
            debug_screenshot.png
            debug_source.html
